### ISSUE TITLE
High-Res Audio view in Timeline

### ISSUE THREAD

**Issue by Marandal-l** [turtletooth/tahoma2d#407] opened 2020-10-23 05:49 UTC
low audio appears as a flat bar on the Timeline.
![Untitled1](https://user-images.githubusercontent.com/35547019/96961044-aa61b480-14b8-11eb-8e60-7f26b85c4bf2.png)

Request: Higher resolution audio viewer on default Timeline.
Example:
![Untitled2](https://user-images.githubusercontent.com/35547019/96961056-b64d7680-14b8-11eb-9096-6ee59ca7a96b.png)

Thanks! :)

**Comment by jeremybullock** [comment] 2020-11-18 04:30
Thanks for the request.  This is a duplicate of #138

**Closed by jeremybullock** 2020-11-18 04:30 UTC
Labels: feature request
